set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Mouse, vi keys, and scrollback
set -g mouse on
setw -g mode-keys vi
set -g history-limit 100000

# vi-style copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel
bind-key ] paste-buffer

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'dracula/tmux'

set -g @dracula-border-contrast true
set -g @dracula-show-flags true

# 当前 focus 的 pane：稍微浅一点
setw -g window-active-style 'bg=#343746'

# 非 focus 的 pane：保持 Dracula 深色
setw -g window-style 'bg=#282a36'

# 可选：边框也稍微明显一点
set -g @dracula-border-contrast true
set -g pane-active-border-style 'fg=#bd93f9'
set -g pane-border-style 'fg=#44475a'

set -g @dracula-plugins "ssh-session network-vpn cpu-usage ram-usage time"
# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
